[package]
name = "mergefs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.11.1"
libc = "0.2"
env_logger = "0.10.0"
log = "0.4.17"
cfg-if = "1.0.0"
